### ISSUE TITLE
Bug réponse durant la mise à jour des infos utilisateurs

### ISSUE THREAD

**Issue by serkansahin** [Aeradriel/birdl-api#10]
Bon quand je fais mes tests sur l'api de prod pour mettre à jour mon compte, j'ai une erreur 500 qui revient à chaque request. Sachant que ma demande passe bel et bien au niveau de la DB...

Petit exemple où j'ai tenté de modifié mon nom de famille : 

![dzd](https://cloud.githubusercontent.com/assets/9954851/10278053/9e86b6c2-6b5a-11e5-82a4-80cb437052d9.png)

voilà :D

**Comment by Aeradriel** [comment]
Un check après le save ? Je check ça ASAP.

**Comment by serkansahin** [comment]
Re, alors j'ai remarqué que quand je me trompe dans ma requête, je reçois un "201 Created" alors que quand je réussi je prend un "500 Internal Server Error".

J'ai notifié un autre bug sur la plateforme web, quand on essaye de mettre à jour son compte depuis son interface de gestion "Mon Compte", ça me met aussi une erreur. Je te screen ça ASAP.

**Comment by serkansahin** [comment]
![image](https://cloud.githubusercontent.com/assets/9954851/10359854/8e899692-6d9c-11e5-95d3-4d11a56b16fe.png)

**Comment by Aeradriel** [comment]
Ca devrait plus sauvegarder si ça crash. Et ça devrait plus crasher si tu ne spécifie pas la date de naissance. Teste et dis moi si c'est ok chez toi.

EDIT : Pour le pb n°1.

**Comment by Aeradriel** [comment]
OK pour le pb n°2.

**Comment by serkansahin** [comment]
Effectivement ça marche nickel pour tout :) !
