### ISSUE TITLE
Impossible de supprimer un utilisateur depuis l'interface d'administration

### ISSUE THREAD

**Issue by serkansahin** [Aeradriel/birdl-api#11]
Tout est dans le titre, j'ai cette erreur :

![bite](https://cloud.githubusercontent.com/assets/9954851/10278378/2dc1a336-6b5d-11e5-92ea-aa3a0ba5ed5e.png)
![bite2](https://cloud.githubusercontent.com/assets/9954851/10278380/2edf14ce-6b5d-11e5-99f6-cadf7bc5d66a.png)

Testé sur la prod directement

**Comment by Aeradriel** [comment]
OK
