### ISSUE TITLE
Ajout de requête Post pour créer un event sur la branche event_api

### ISSUE THREAD

**Issue by CrisCR** [Aeradriel/birdl-api#12]

**Comment by Aeradriel** [comment]
post '/events/create'

mandatory params : name (str), desc (str), type ('FaceToFace', 'GroupEvent', 'TourismTour'...), min_slots (int), max_slots (int), date (str : YYYY/MM/DD)

Teste et dis moi si c'est bon.

EDIT : Pas besoin de json

**Comment by CrisCR** [comment]
Il manque les param "location", "langue" et "ending_date", je vais quand même tester la requête.

**Comment by Aeradriel** [comment]
En effet, j'ai fais le truc à l'arrache, j'avais pas le temps. Je vais refaire ça proprement.

**Comment by Aeradriel** [comment]
OK
